name: Deploy With PatchBurger Security Scan

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - uses: Security-Academe-7-FiveGuys/PatchBurger@v1
        with:
          deploy-on-risk: "false"
          dependency-files: |
            camera-blocker-backend/package.json:package.json:npm
